let events = ["08:00 Reunião", "10:30 Consulta", "15:00 Treinamento"];
console.log(manageEvents(events, "12:00 Almoço", 2, "10:30 Consulta"));

let students = ["Ana", "Bruno", "Carlos", "Daniel"];
console.log(modifyAttendanceList(students, "Eduarda", 2, "Carlos"));

let queue = ["Jogador1", "Jogador2"];
console.log(manageQueue(queue));

let catalog = ["O Senhor dos Anéis", "1984", "Dom Casmurro"];
console.log(findBookIndex(catalog, "1984"));
